// schemas/builderBlock.js
export default {
  name: 'builderBlock',
  type: 'array',
  title: 'Builder Block',
  of: [
    { type: 'heroSection' },
    { type: 'textBlock' },
    { type: 'imageBlock' },
    { type: 'videoBlock' },
    { type: 'buttonBlock' },
    { type: 'columnBlock' },
    { type: 'containerBlock' },
    { type: 'headingBlock' },
    { type: 'spacerBlock' },
    { type: 'fontUpload' },
    { type: 'footerSetting' },
    { type: 'menu' },
    { type: 'menuitem' },
    { type: 'post' },
    { type: 'siteSettings' },
    { type: 'imageWithTextSection' },
    { type: 'richTextSection' },
    { type: 'videoWithTextSection' },
    { type: 'faqSection' },
    { type: 'newsletterSignupSection' },
  ],
};
